### ISSUE TITLE
Исправить скрипты миграции даннных в таблицу

### ISSUE THREAD

**Issue by ArtemNemtsov** [s0me0ne7/Otus_HW2#2]
https://github.com/s0me0ne7/Otus_HW2/blob/d3e2108877b3a3b2fda88e01fe0089ad9be98c6e/Otus_HW2/DbScripts/Otus_HW2_InsertScript.sql#L3
Излишний код. Для таблицы clients предлагаю обойтись скриптом типа: 
INSERT INTO table_name (column1, column2, column3, ...)
VALUES (value1, value2, value3, ...);

**Comment by s0me0ne7** [comment]
Спасибо, поправил.
