### ISSUE TITLE
Изменить метод работы с консолью

### ISSUE THREAD

**Issue by ArtemNemtsov** [s0me0ne7/Otus_HW2#3]
https://github.com/s0me0ne7/Otus_HW2/blob/e37848b2048124c4240c8bfa57af1b3532debe29/Otus_HW2/Program.cs#L20
Т.К. подразумевается чтение одного символа, правильнее использовать метод ReadKey c последующей проверкой, вместо ReadLine

**Comment by s0me0ne7** [comment]
Согласен, спасибо, поправил.
