### ISSUE TITLE
Переименовать метод в соответствие с рекомендациями

### ISSUE THREAD

**Issue by ArtemNemtsov** [s0me0ne7/Otus_HW2#4]
https://github.com/s0me0ne7/Otus_HW2/blob/e37848b2048124c4240c8bfa57af1b3532debe29/Otus_HW2/Program.cs#L20
Предлагаю переименовать метод ClientProductsAdd в AddClientProducts. Более правильно, если начало метода содержит глагол, по аналогии с методами выше 

2. Рекомендации
2.1 Именование методов
Используйте конструкцию глагол-объект для именования методов
ShowUserInfo()

**Comment by s0me0ne7** [comment]
Поправил
